#!/bin/sh
set -e -u
cp -r tests "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
py3versions -i \
| tr ' ' '\n' \
| xargs -I {} env PYTHONWARNINGS=d PYTHONHASHSEED=random {} \
  -m pytest -vv 2>&1

# vim:ts=4 sw=4 et
